package com.github.markojevtic.restfulapi.resource.dto;

import com.github.markojevtic.restfulapi.repository.entity.TenderStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.hateoas.ResourceSupport;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.constraints.Size;
import java.util.List;

@Builder
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "Represents a tender object")
public class TenderDto extends ResourceSupport {

    @Size(max = 36)
    @ApiModelProperty( notes = "The unique identifier of tender, it's auto-generated by application.(Max length 36)", readOnly = true, example = "Read-only, in post will be ignored.")
    private String tenderId;

    @Size(max = 36)
    @ApiModelProperty( notes = "The id of tender's issuer.(Max length 36)", example = "max.issuer")
    private String issuerId;

    @Size(max = 500)
    @ApiModelProperty( notes = "Description of the tender.(Max length 500)", example = "Build the house.")
    private String description;

    @ApiModelProperty( notes = "Status of the tender.", readOnly = true)
    private TenderStatus status;


    public static class TenderDtoBuilder extends LombokDtoBuilder<TenderDto> {
        //Will be created by lombok
    }
}
